changed DeleteFolderItems to soft-delete and fix of null warnings
LightJack05/AnonKey-Backend pull request #73
Opened 2024-10-11 09:31 UTC by MLB-on

- Fix null warnings. #61 
- soft deletion of Credentials when Folder is deleted recursevly. closes #72

2024-10-11 13:57 UTC, Jannik-Hm commented on ApiEndpoints/Folders/Delete.cs
> +            item.DeletedTimestamp = (long)DateTime.UtcNow.Subtract(DateTime.UnixEpoch).TotalSeconds;
Hey, just my understanding: does this only set the DeletedTimeStamp to the current time?

We need to set the folderUuid to `null` as well. Otherwise the credential will have a non-existing folder, once restored.

2024-10-11 15:32 UTC, LightJack05 requested changes
See comment by @Jannik-Hm

2024-10-11 15:34 UTC, LightJack05 commented on ApiEndpoints/Folders/Update.cs
Would be better if you fix null warnings in a separate PR, keep one PR to one fix/feature. Fine for now though. ;)

2024-10-12 08:48 UTC, MLB-on commented on ApiEndpoints/Folders/Delete.cs
> +            item.DeletedTimestamp = (long)DateTime.UtcNow.Subtract(DateTime.UnixEpoch).TotalSeconds;
You are right.
I have added the missing line.

2024-10-12 11:12 UTC, LightJack05 approved these changes

2024-10-12 11:13 UTC, merged