Compiler Warnings for credentials endpoint silenced
LightJack05/AnonKey-Backend pull request #74
Opened 2024-10-13 17:18 UTC by zak-off-zak

2024-10-13 20:07 UTC, LightJack05 requested changes
Just some minor gripes.

2024-10-13 20:07 UTC, LightJack05 commented on ApiEndpoints/Credentials/Create.cs
> +        AnonKey_Backend.Models.User? FetchedUser = databaseHandle.Users.SingleOrDefault(u => u.Username == user.Identity.Name);
Since you only use the username from the ClaimsPrincipal object, consider passing that in without everything else.

2024-10-13 20:07 UTC, LightJack05 commented on ApiEndpoints/Credentials/Create.cs
> +        if (FetchedUser is null) throw new ArgumentNullException();
You may want to consider a different exception type here, since it is not an argument that is null.

2024-10-13 20:07 UTC, LightJack05 commented on ApiEndpoints/Credentials/GetAll.cs
> +        if (user.Identity is null) throw new ArgumentNullException();
Same here as in the other comment, you only use the username, maybe only pass that into this method.

2024-10-14 05:46 UTC, zak-off-zak commented
Thank you for the feedback! Here is an attempt  to improve some minor details ;)

2024-10-14 06:05 UTC, LightJack05 requested changes

2024-10-14 06:05 UTC, LightJack05 commented on ApiEndpoints/Credentials/Create.cs
> +    private static Models.Credential CreateNewCredential(ApiDatastructures.Credentials.Create.CredentialsCreateRequestBody requestBody, string? Username, Data.DatabaseHandle databaseHandle)
Naming Convention: Method parameters should be in camelCase

2024-10-14 06:05 UTC, LightJack05 commented on ApiEndpoints/Credentials/Create.cs
> +        if (FetchedUser is null) throw new NullReferenceException();
This is fine for now, maybe add a message to the exception.
Usually a custom exception type would probably be better, but lets not get into that at this time.

2024-10-14 06:05 UTC, LightJack05 commented on ApiEndpoints/Credentials/GetAll.cs
> +    private static CredentialsGetAllResponseBody GetAllCredetials(string? Username, DatabaseHandle databaseHandle)
Naming Convention: Method parameters should be in camelCase

2024-10-14 06:05 UTC, LightJack05 commented on ApiEndpoints/Credentials/GetAll.cs
> +        if (FetchedUser is null) throw new ArgumentNullException();
Also adjust this exception please

2024-10-14 10:27 UTC, zak-off-zak commented
Tried fixing the above mentioned points

2024-10-14 10:32 UTC, LightJack05 approved these changes

2024-10-14 10:32 UTC, merged